### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by leymannx**
Added usage info about how to configure composer.json to make Drush Launcher do its work.

### CODE REVIEW

**Comment by leymannx** [comment]
Oops I only now saw https://github.com/drush-ops/drush-launcher/pull/40.

Hope this one makes it a little simpler.

**Comment by weitzman** [comment]
This confuses more than helps IMO. Setting up your composer project is best explained by drupal-project IMO.

**Comment by weitzman** [comment]
Also drush/drush is not this project.

**Comment by leymannx** [comment]
The point is that drupal-project is not required to use Drush Launcher. That you basically can use it with any age-old Drupal 8/7/6/.. project and that the described usage is the minimal requirement to make Drush Launcher work. Which is far from obvious in my opinion.

**Comment by leymannx** [comment]
Of course Drush Launcher is not drush/drush what do you mean by that?

**Comment by leymannx** [comment]
Maybe "Usage" is not the best heading. Maybe "Requirememts" is better.

**Comment by weitzman** [comment]
I'm starting to understand that you want to explain that this project can be used by composer projects not built from drupal-project. I'm fine with docs that briefly explain that but I dont this PR does it clearly enough yet. Ithink the composer.json approach confuses more than helps because you are not referring to this project but to a whole other project.

**Comment by leymannx** [comment]
I'm not sure I get you here. Could you give me a rough outline of how that could look like and I do the fine-tuning. It's only I'd wish I had the information I made to this PR months earlier. And I think that it would help a lot to explain Drush Launcher. How to do that without referring to Drush?

**Comment by leymannx** [comment]
I now saw that using Drush Launcher without the Composer template for Drupal projects can break a whole project when using `drush up`. The minimal approach from this PR only works for running basic commands.

**Pull request closed without merging**
